### ISSUE TITLE
mouse scrolling suggestion forwarding pgn

### ISSUE THREAD

**Issue by mvkrdndm** [lukasmonk/lucaschess#11]
![image 001](https://cloud.githubusercontent.com/assets/16892782/14797143/cb6814cc-0b39-11e6-89b9-9dd95ff8da86.jpg)
i think i accidently deleted a post i was reguesting the mouse scroll feature for pgn forwarding when the cursor on the  move list  if you scroll down and pgn goest forward but when the cursor on the chess board when you scroll down pgn goes backward it should be general and regardless the mouse cursor place like in chessbase when you scroll down it always forwards the pgn regardless of the position of the mouse cursor

**Comment by lukasmonk** [comment]
Your question:

hello when scrolling with middle mouse it is confusing.
1-when cursor on area A you had to scroll top to go forward at pgn
2-when cursor on area B you had to scroll down to go forward at pgn
3-when cursor on the outside of the area A and B nothing happens if you scroll
this is confusing.my suggestion is it is one way and regardless the cursor on which area.and i assume standart way of doing this it should be if you scrool down pgn should go forward like chessbase products

My answer:

To the future 10 release, some time ago, I changed the program to match the behavior on the table PGN and on the board. 
Sorry, I don´t know if new behaviour is the same as chessbase products, this is not a factor in my decisions.

I note the point 3 to study.

**Comment by mvkrdndm** [comment]
thanks for answer it is not important chessbase products ok ,if all areas has same behaviour it would be perfect because it is really confusing when mouse cursor when in  area A and area B it acts opposite behaviour
